**TASK:** import numpy

In [1]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [3]:
x = np.array([1,2,3])
x


array([1, 2, 3])

**TASK:** define (2 x 2) matrix 'A' 


In [6]:
A = np.array([[1,2],[2,3]])
A

array([[1, 2],
       [2, 3]])

**TASK:** define (2 x 2) matrix 'B'

In [8]:
B = np.array([[2,3],[4,5]])
B

array([[2, 3],
       [4, 5]])

**TASK:** check the type of 'x'

In [11]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [13]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [14]:
x.shape

(3,)

**TASK:** check the type of 'A'

In [10]:
type(A)
A.shape

(2, 2)

**TASK:** 

In [ ]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

In [16]:
def have_same_shape(array_1, array_2):
    '''checks if two arrays have same shape'''
    s1 = array_1.shape
    s2 = array_2.shape 
    if s1 == s2: 
        return True
    else: 
        print("Arrays must have the same shape!")
        return False 


**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [18]:
have_same_shape(A, x
            )

Arrays must have the same shape!


False

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [21]:
have_same_shape(A, B)

True

**TASK:** 

In [ ]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


In [23]:
def matrix_addition(array_1, array_2):
    '''Matrix addition'''
    if have_same_shape(array_1, array_2):
        C = array_1 + array_2 
        return C 
    else: 
        return "Same shape is needed to do addition!"


**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [34]:
print(A) 
print(B)
matrix_addition(A,B)

[[1 2]
 [2 3]]
[[2 3]
 [4 5]]


array([[3, 5],
       [6, 8]])

**TASK:** 

In [1]:
"""
Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [75]:
def multiple_matrix_addition(lst_of_arr):
    for x in lst_of_arr:
        new_array = matrix_addition(x,x)
        new_array += new_array
    return new_array
    
list_arr = [A,A,B,B,B] 

multiple_matrix_addition(list_arr)

array([[ 8, 12],
       [16, 20]])

**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


**TASK:** 

In [ ]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

In [58]:
def can_multiply(array_a, array_b):
    if array_a.shape[1] == array_b.shape[0]:
        arr_c = array_a.dot(array_b)
        print(arr_c.shape)
        return True
    else: 
        print('Matrices can not be multiplied')
        return False
    

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [52]:
can_multiply(A,B)


(2, 2)
2


**TASK:**  define matrix (3 x 2) matrix C

In [55]:
C = np.array([[1,2],[2,3],[4,5]])
print(C.shape
    )

(3, 2)


**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [49]:
can_multiply(A,C)

Matrices can not be multiplied


False

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [59]:
can_multiply(C,A)
#It is different, because the the column in A and row in B are the same, so they can be multiplied, but when you switch the order, the rows in A and column in B are different,
#and cannot be multiplied

(3, 2)


True

**TASK:** 

In [ ]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

In [68]:
def matrix_multiplication(array_a, array_b):
    '''multiplies 2 matrices together'''
    if array_a.shape[1] == array_b.shape[0]:
        arr_c = array_a.dot(array_b)
        return arr_c
    else:
        return 'Cannot be multiplied, arrays are incompatible'
    


**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [69]:
matrix_multiplication(C,B)


array([[10, 13],
       [16, 21],
       [28, 37]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [71]:
print(A)
print(C)
matrix_multiplication(A,C)

[[1 2]
 [2 3]]
[[1 2]
 [2 3]
 [4 5]]


'Cannot be multiplied, arrays are incompatible'