# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
b = np.zeros(10)
b[4] = 1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
c = np.random.randint(10,50, size = 10 )
c

array([27, 27, 34, 45, 36, 22, 21, 38, 24, 21])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [15]:
c[::1]=c[::-1]
c

array([21, 24, 38, 21, 22, 36, 45, 34, 27, 27])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
d = np.random.randint(0,9, size=(3,3))
d

array([[5, 8, 0],
       [3, 2, 1],
       [0, 6, 0]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [23]:
e = np.array([1,2,0,0,4,0])
e[e > 0]

array([1, 2, 4])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [26]:
f = np.random.random(size = (3,3,3))
f

array([[[0.00625359, 0.0326326 , 0.7760085 ],
        [0.09827977, 0.31457852, 0.94058072],
        [0.038921  , 0.97164664, 0.22538474]],

       [[0.70328676, 0.67110777, 0.14112319],
        [0.85791867, 0.42820816, 0.8557757 ],
        [0.74731836, 0.19524937, 0.45689097]],

       [[0.15802072, 0.73199801, 0.62816128],
        [0.34575143, 0.90312033, 0.5468153 ],
        [0.40342117, 0.4347131 , 0.82780305]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [39]:
g = np.random.random(size = (10,10))
gmin = np.min(g)
gmax = np.max(g)
print('minimum value of g is ' + str(gmin) + ' and the maximum value of g is ' + str(gmax))

minimum value of g is 0.003793478151105756 and the maximum value of g is 0.9840789067154954


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [63]:
h = np.random.random(size= (30))
hmean = np.mean(h)
print(h)
hmean

[0.66916509 0.9663257  0.57536769 0.84759071 0.39364464 0.99259999
 0.05049333 0.90398355 0.73795502 0.27844505 0.20499092 0.47632756
 0.34895933 0.73605301 0.8112381  0.88627973 0.52532826 0.60332694
 0.39671219 0.85988903 0.48171563 0.96603791 0.01943825 0.04089412
 0.30650033 0.43130276 0.94157919 0.05918639 0.57409373 0.54915259]


0.5544858909487352

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [81]:
i = np.ones((3,3))
i.ndim
i[1,1] = 0
i

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [94]:
#label each row / column of interest and replace it with zero. 
i[1,1] = 2 #replaced so you can see me changing the border only. 
i[0,0:] = 0
i[0:,0] = 0
i[-1,:-1] = 0
i[:-1,-1] = 0 
print(i)

[[0. 0. 0.]
 [0. 2. 0.]
 [0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [96]:
#The result is False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [99]:
j = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
j

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [101]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [103]:
k = np.random.random((5,5))
kmax = k.max() 
kmin = k.min()
k= (k-kmin)/(kmax-kmin)
print (k)

[[8.81825838e-01 5.19038569e-01 9.43846140e-01 9.29275771e-01
  4.80545462e-01]
 [4.01925888e-01 5.54316229e-01 9.94577350e-01 5.68741887e-03
  9.67866672e-04]
 [8.31670458e-01 4.66014539e-01 7.40960838e-02 2.79260559e-01
  2.53025048e-01]
 [0.00000000e+00 6.48868877e-01 1.00000000e+00 8.16961692e-01
  3.21621390e-01]
 [9.25140853e-01 2.08507804e-01 3.44131898e-01 7.39343405e-01
  2.43211240e-01]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [110]:
l = np.array([1,2,3,4,5,6,7,8,9,10])
neg = (l > 3) & (l < 8) 
l[neg] *= -1 
print( l)

[ 1  2  3 -4 -5 -6 -7  8  9 10]


#### 29. How to round away from zero a float array ? (★☆☆)

In [113]:
m = np.array([1.4,2.2,3.3,4.4])
m2 = np.round(m,0)
m2 

array([1., 2., 3., 4.])

#### 30. How to find common values between two arrays? (★☆☆)

In [116]:
#using the np.intersect1d(<array1>, <array2>)
array1 = np.array([1,2,3,4,5,6])
array2 = np.array([2,4,5,6,7 ])
intersect = np.intersect1d(array1, array2)
intersect

array([2, 4, 5, 6])

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [117]:
# The expression is False 

<ipython-input-117-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [131]:
def generator():
    """generates 10 integers"""
    for n in range(10):
        yield n
        
n = np.fromiter(generator(), dtype= float, count= -1 )
n 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [136]:
v1 = np.linspace(0,1,12)[1:-1]
print(v1)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [149]:
v2 = np.random.random(10)
v2.sort()
v2

array([0.03812737, 0.04367694, 0.12463706, 0.16241287, 0.71366382,
       0.73143797, 0.74538153, 0.75662621, 0.77676819, 0.79555407])

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [167]:
a = np.random.randint(1,3,7)
b = np.random.randint(1,3,7)
equal = np.allclose(a,b)
print(equal)

False


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [181]:
a = np.random.random(10) 
a[a.argmax()]=0
print(a)



[0.94639533 0.87996265 0.58810484 0.95984809 0.86292723 0.59966832
 0.0806971  0.05565573 0.         0.29214551]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [183]:
a = np.arange(50)
b = np.random.uniform(0,50)
index = (np.abs(a-b)).argmin()
print(a[index])

23


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [193]:
a = np.array([2.0,3.0,4.0,5.0])
a = a.astype(dtype='int32')
a

array([2, 3, 4, 5])

#### 59. How to sort an array by the nth column? (★★☆)

In [195]:
a= np.array([[2,4,6],[2,1,4],[3,4,6]])
a = a[a[:,1].argsort()]
print(a)

[[2 1 4]
 [2 4 6]
 [3 4 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [202]:
nums = np.random.randint(0,2,(3,15))
print(nums)
print((~nums.any(axis=0)).any())

[[1 1 1 0 0 1 1 0 0 1 0 1 1 0 1]
 [0 0 1 0 0 1 1 1 1 1 1 0 1 0 0]
 [1 1 1 1 1 1 0 0 1 0 1 1 0 1 1]]
False


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [205]:
a = np.array([1,2,3,4,5])
numz = 3
a0 = np.zeros(len(a)+(len(a)-1)*(numz))
a0[::numz+1] = a 
print(a0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 72. How to swap two rows of an array? (★★★)

In [206]:
a = np.arange(16).reshape(4,4)
a[[0,1]] = a[[1,0]]
print(a)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [213]:
#Negating a boolean 
a = np.random.randint(0,2,50)
print(a)
print(np.logical_not(a, out=a))

#changing the sign of float inplace
a = np.random.uniform(-1.0,1.0,10)
print(a)
print(np.negative(a, out=a))


[0 1 0 1 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 0 0 1 0 0 0 0 1 0
 0 1 0 1 1 1 0 0 1 0 1 1 1]
[1 0 1 0 1 0 1 0 0 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 1 1 0 1 1 1 1 0 1
 1 0 1 0 0 0 1 1 0 1 0 0 0]
[ 0.62559541  0.40881478  0.05752489  0.42582459 -0.11765493 -0.39282008
 -0.19723576 -0.65905895  0.57717321 -0.85936005]
[-0.62559541 -0.40881478 -0.05752489 -0.42582459  0.11765493  0.39282008
  0.19723576  0.65905895 -0.57717321  0.85936005]


#### 83. How to find the most frequent value in an array?

In [224]:
a= np.random.randint(0,10,100)
print(a)
print('most frequent number is', np.bincount(a).argmax())

[5 3 6 8 2 6 9 5 4 3 0 2 5 0 7 2 5 8 4 0 2 6 6 9 0 4 1 5 9 8 2 7 5 2 0 9 7
 9 8 9 4 7 0 2 8 9 6 9 3 6 5 3 9 2 2 6 9 7 2 8 6 2 2 4 9 6 6 8 4 2 4 7 8 2
 9 2 6 9 0 7 6 6 9 1 8 0 9 3 2 8 3 1 0 7 5 2 9 2 0 7]
most frequent number is 2


#### 89. How to get the n largest values of an array (★★★)

In [229]:
a = np.arange(100)
np.random.shuffle(a)
n = 5 
print(a[np.argsort(a)[-n:]])

[95 96 97 98 99]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [240]:
a = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, a.dtype.itemsize * a.shape[1])))
_, idx = np.unique(T, return_index=True)
uA = a[idx]
print(uA)

[[0 0 0]
 [0 0 0]
 [1 1 0]
 [0 1 1]]
